version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8080" # Map host port 8082 to container port 8080
    environment:
      - ATLASDB_URL=${ATLASDB_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - SECRET=${SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   - some_other_service
