version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace  # Mount the whole project to /workspace (host → container)
